### ISSUE TITLE
[noetic] callback error

### ISSUE THREAD

**Issue by fvillml** [udacity/odom_to_trajectory#2]
When running the node in noetic I got the following error

```shell
[ERROR] [1626727220.718753, 412.490000]: bad callback: <function callback at 0x7fe2158b1ee0>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/user/ROS/test2_ws/src/turtlebot_sim_noetic/odom_to_trajectory/scripts/path_odom_plotter.py", line 50, in callback
    path.poses.pop(0)
IndexError: pop from empty list

```

**Comment by abhiojha8** [comment]
We don't have any updates for noetic yet. The code is expected to work in Kinetic only.
